HTTP/1.1 200 OK
Content-Type: text/html; charset=UTF-8
Server: netcat!

<!doctype html>
<html>
<body>
<h1>A webpage served by netcat</h1>
</body>
</html>

POST /CSP/report HTTP/1.1
Host: 158.160.13.100:7001
Accept: application/json
Content-Type: application/json
Content-Length: 210

{
    "csp-report": 
    {
        "referrer": "http://referrer",
        "document-uri":"http://document",
        "blocked-uri": "http://blocked",
        "violated-directive": "some-directive",
        "original-policy":"csp-policy",
        "disposition":"disposition"
    }
}
